# Generated by Django 5.1.3 on 2024-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'Cancelled'), ('Order Successful Complete', 'Order Successful Complete')], default='pending', max_length=30),
        ),
    ]
